sdk: "/Users/lars/Dev/code/rhodes"
sdkversion: 3.2.1
name: newapp
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.newapp
  BundleURLScheme: newapp
wp:
  productid: '3365b4d0-fc39-012e-268a-482a141043d9'
symbian:
  uid: '0xe22a2819'
android:
  version: 2.1

extensions: ["json", "another-extension"]
